comment: false
coverage:
  status:
    project: false
    patch:
      default:
        target: 80%
        threshold: 0%
        base: auto
        if_ci_failed: error
        if_no_uploads: success
        if_not_found: success
fixes:
  - "/workspace/::"
